# Generated by Django 5.2 on 2026-03-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_add_review', 'Can add review'), ('can_delete_review', 'Can delete review'), ('can_delete_any_review', 'Can delete any review')]},
        ),
    ]
