# Generated by Django 5.2 on 2026-04-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
