# Generated by Django 5.2 on 2026-04-02 17:31

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brand/')),
            ],
            options={
                'permissions': [('can_manage_body_style', 'Can manage Body Style')],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brand/')),
            ],
            options={
                'permissions': [('can_manage_brands', 'Can manage brands')],
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'permissions': [('can_manage_transmission', 'Can manage transmission')],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('speed', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('image_1', models.ImageField(upload_to='car_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('body_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='catalog.bodystyle')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='catalog.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL)),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='catalog.transmission')),
            ],
            options={
                'permissions': [('can_add_car', 'Can add car'), ('can_edit_car', 'Can edit car'), ('can_edit_any_car', 'Can edit any car'), ('can_delete_car', 'Can delete car'), ('can_delete_any_car', 'Can delete any car')],
            },
            managers=[
                ('all_cars', django.db.models.manager.Manager()),
            ],
        ),
    ]
