# Generated by Django 5.2 on 2026-03-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodystyle',
            options={'permissions': [('can_manage_body_style', 'Can manage Body Style')]},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'permissions': [('can_manage_brands', 'Can manage brands')]},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('can_add_car', 'Can add car'), ('can_edit_car', 'Can edit car'), ('can_edit_any_car', 'Can edit any car'), ('can_delete_car', 'Can delete car'), ('can_delete_any_car', 'Can delete any car')]},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'permissions': [('can_manage_transmission', 'Can manage transmission')]},
        ),
    ]
