# Generated by Django 5.2 on 2026-03-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aihistory',
            options={'permissions': [('can_view_ai_history', 'Can view ai history'), ('can_delete_ai_history', 'Can delete ai history')]},
        ),
        migrations.AlterModelOptions(
            name='airecommendation',
            options={'permissions': [('can_ask_ai', 'Can ask AI')]},
        ),
    ]
